name: Web app pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - 'day5'
    paths:
      - 'codeacademy-nextjs/**'
      - '.github/workflows/pipeline.yaml'

jobs:
  build_and_push_to_ecr:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{secrets.AWS_ACCESS_KEY_ID}}
          password: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            ${{ vars.REGISTRY }}/coeacademy-nextjs:latest
            ${{ vars.REGISTRY }}/coeacademy-nextjs:${{ github.sha }}
      

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_ecr

    steps:
      - name: Get public IP 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        run: |
          ip_address=$(aws ec2 describe-instances --filters 'Name=tag:Name,Values=${{ vars.EC2_NAME }}' --query 'Reservations[].Instances[].PublicIpAddress' --output text)
          echo "EC2_PUBLIC_IP=$ip_address" >> $GITHUB_ENV

      - name: Pull latest in EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: 'ec2-user'
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            aws ecr get-login-password | docker login --username AWS --password-stdin ${{ vars.REGISTRY }}
            docker pull ${{ vars.REGISTRY }}/coeacademy-nextjs:latest
            docker rm --force ui_app
            docker run -d --name ui_app -p 80:80 ${{ vars.REGISTRY }}/coeacademy-nextjs:latest